name: Build Docker image
 
on:
  push: {}
 
jobs:
    compile:
        name: Compile rmarkdown
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            run: docker run --rm -v ${{ github.workspace }}:/doc docker.io/koenleuveld/rmarkdown2pdf:0.2.1 myrmd.Rmd
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              path: ${{ github.workspace }}/myrmd.pdf

##https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
